service: slackbot

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

functions:
  slackbot:
    handler: index.handler
    events:
      - http:
          path: slackbot-action
          method: post